---
# Start of Service clients
service-definitions:
-  ApplePay: &ApplePay
      discoveryId: c
      path: /wallet/pay
      class: ApplePayRestClient
      type: apple

-  PayPal: &PayPal
      discoveryId: TPS
      path: /wallet/pay
      service-class: PayPalRESTClient
      type: samsung

## End of Service Client definitions

tenants:
    - tenant:
        countryCode: US
        businessCode: GCB
        channel: MOB
        strategy: AnyOfByType
        backends:
        - <<: *ApplePay
        - <<: *PayPal
